### ISSUE TITLE
Can not found FPS-Start_Large object in the Unity Hierarchy window

### ISSUE THREAD

**Issue by fattahbakir** [spatialos/gdk-for-unity-fps-starter-project#144]
#### Description
Describe your issue.
 am trying to run this demo, but failed. 
In Get started: 2 - Open the FPS Starter Project, I open FPS-SimulatedPlayerCoordinator, I can not found FPS-Start_Large object in the Unity Hierarchy window & if I bake the file the navmesh disappears. When building the whole project this does not give me a way in the workers to add simulated players.

## Expected behaviour
Expect to find FPS-Start_Large in the Hierarchy window.

## Current behaviour
can not found FPS-Start_Large object in the Unity Hierarchy window. 

Windows 10 & unity 3.9f1

**Comment by zeroZshadow** [comment]
Which of the steps in https://docs.improbable.io/unity/alpha/content/get-started/build-workers are you stuck on?

**Comment by fattahbakir** [comment]
Hey, I am following the guide on youtube which is easier as a tutorial video, 
https://www.youtube.com/watch?v=6PNDBYtIimw&t=519s

and I am stuck on unable to see in the hierarchy window the FPS-Start_Large when I try to click on Simulated Players to rebake the navmesh.

![image](https://user-images.githubusercontent.com/17296216/54865588-63598d80-4d70-11e9-87d1-892379a6a45c.png)

This results in the simulated players coordinator not showing up when I build the game and upload it on the cloud like below.

![image](https://user-images.githubusercontent.com/17296216/54865616-b6cbdb80-4d70-11e9-9d02-3a77efa78347.png)

**Comment by zeroZshadow** [comment]
The video is out of date since our 0.2.0 release, so I recommend following the documentation instead.

**Comment by fattahbakir** [comment]
Working perfectly.
Thanks
