### ISSUE TITLE
Clients may hang when quitting the game

### ISSUE THREAD

**Issue by jamiebrynes7** [spatialos/gdk-for-unity-fps-starter-project#188]
**Affects:** Release v0.2.0 and up
**Internal Ticket:** [UTY-1968](https://improbableio.atlassian.net/browse/UTY-1968)

---

#### Description

When quitting a standalone client, the process may hang (seemingly forever).

#### Workaround

Force quit the application via the Task Manager or the Activity Monitor.

**Comment by zeroZshadow** [comment]
Will be fixed on v0.2.3

**Comment by jamiebrynes7** [comment]
`v0.2.3` has been released! https://github.com/spatialos/gdk-for-unity-fps-starter-project/releases/tag/0.2.3
