### ISSUE TITLE
Assembly Refernce Error

### ISSUE THREAD

**Issue by tjones0808** [spatialos/gdk-for-unity-fps-starter-project#252]
We are accepting issues and we want your [feedback](https://github.com/spatialos/gdk-for-unity#give-us-feedback).

-------

#### Description
Describe your issue.
Seems like it can find the correct reference. Am i missing something? I am following the tutorial directly.

> Assets\Fps\Resources\Prefabs\UnityClient\HealthPickupClientVisibility.cs(26,65): error CS0234: The type or namespace name 'Update' does not exist in the namespace 'Fps.HealthPickup' (are you missing an assembly reference?)

> Assets\Fps\Resources\Prefabs\UnityGameLogic\HealthPickupServerBehaviour.cs(9,17): error CS0103: The name 'WorkerUtils' does not exist in the current context

## Expected behaviour

I expect the code to build.

## Steps to reproduce

1.
2.
3.
4.

## Environment
 The setup health tutorial

**Comment by zeroZshadow** [comment]
Does the assembly definition for your files include a reference to the `Improbable.Gdk.Generated` asmdef?

You seem to have put the source files in the `Resources/Prefabs` folder. This might not be included by the default `BlankProject`  asmdef that is included in the blank project.

**Comment by tjones0808** [comment]
Ok, moved to correct file locations. WorkUtils is okay but still can't find the HealthPickup.Update method.. Thanks for the help!

**Comment by shanepadgett** [comment]
> Ok, moved to correct file locations. WorkUtils is okay but still can't find the HealthPickup.Update method.. Thanks for the help!

That's because there is a namespace collision. HealthPickup is also a namespace under FPS as well as a class under Pickups. Simple fix is to change the signature to `private void OnHealthPickupComponentUpdated(Pickups.HealthPickup.Update update)` so that you explicitly access the HealPickup class.

**Comment by jamiebrynes7** [comment]
Hey @tjones0808 & @shanepadgett, thanks for the report! 

We've updated the code samples on the health pickups class to fix both the namespace collision issue and the `WorkerUtils` issue.
