### ISSUE TITLE
Errors errors everywhere

### ISSUE THREAD

**Issue by Olaowo** [spatialos/gdk-for-unity-fps-starter-project#275]
[Editor.log](https://github.com/spatialos/gdk-for-unity-fps-starter-project/files/4730294/Editor.log)
[Editor-prev.log](https://github.com/spatialos/gdk-for-unity-fps-starter-project/files/4730295/Editor-prev.log)
[symbol_upload.log](https://github.com/spatialos/gdk-for-unity-fps-starter-project/files/4730296/symbol_upload.log)
[upm.log](https://github.com/spatialos/gdk-for-unity-fps-starter-project/files/4730297/upm.log)

We are accepting issues and we want your [feedback](https://github.com/spatialos/gdk-for-unity#give-us-feedback).

-------

#### Description
Describe your issue.
Trying the spatialos FPS started pack on Unity, follwed the set-up stage, 

## Current behaviour

when I open the project on the unity version 2019 3.15f1, I got about 166 errors almost all Are saying "The type or namespace name 'Worker' does not exist in the namespace 'Improbable' (are you missing an assembly reference"

**Comment by jamiebrynes7** [comment]
Hey @Olaowo, can you attach your Unity editor logs? 

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by Olaowo** [comment]
> Hey @Olaowo, can you attach your Unity editor logs?
> 
> https://docs.unity3d.com/Manual/LogFiles.html

done

**Comment by jamiebrynes7** [comment]
Okay so looking at the Editor logs, you mentioned that you tried to use the FPS project, but the logs seem to be trying to compile https://github.com/spatialos/gdk-for-unity instead. For example I can see these file paths in the compile logs:

```
"D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\AssemblyInfo.cs"
"D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Attributes\DisableAutoRegisterAttribute.cs"
"D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Attributes\RemoveAtEndOfTickAttribute.cs"
"D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\CodegenAdapters\IComponentReplicationHandler.cs"
"D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Collections\EntityRangeCollection.cs"
"D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Collections\ListPool.cs"
```

Could you give the exact reproduction steps for this issue?

**Comment by Olaowo** [comment]
> Okay so looking at the Editor logs, you mentioned that you tried to use the FPS project, but the logs seem to be trying to compile https://github.com/spatialos/gdk-for-unity instead. For example I can see these file paths in the compile logs:
> 
> ```
> "D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\AssemblyInfo.cs"
> "D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Attributes\DisableAutoRegisterAttribute.cs"
> "D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Attributes\RemoveAtEndOfTickAttribute.cs"
> "D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\CodegenAdapters\IComponentReplicationHandler.cs"
> "D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Collections\EntityRangeCollection.cs"
> "D:\Unity Projects\gdk-for-unity\workers\unity\Packages\io.improbable.gdk.core\Collections\ListPool.cs"
> ```
> 
> Could you give the exact reproduction steps for this issue?

Okay. I follwed the set-up from the link "https://documentation.improbable.io/gdk-for-unity/docs/fps-1-set-up#section-4-install-the-gdk-dependencies"

- I made a spatial os account

- Configure my netwroks to allow TCP port 444 and 443 outbounds
- Install the Unity version 2019 3.15f.1(latest one at the time from UnityHUB)
- Install the netcore sdk but 3.1 instead of 2.22
- Ran the spatialos installer and installed them in folder of my choosing
- clone the git to the folder path where i keep my unity projects
- opened the the unity project folder from inside the resulted git cloned in path "Unity Projects\gdk-for-unity\workers\unity"

Then got this errors,

**Comment by jamiebrynes7** [comment]
What `git` command did you run to clone the Unity project? 

```
git clone git@github.com:spatialos/gdk-for-unity-fps-starter-project.git
```

or 

```
git clone git@github.com:spatialos/gdk-for-unity.git
```

or something else?

**Comment by paulbalaji** [comment]
The `spatialos/gdk-for-unity` repository is where the GDK source lives before we publish the individual packages. It does not contain the FPS or Blank projects, which live in different repositories of their own.

To try the FPS project, you should be cloning the `spatialos/gdk-for-unity-fps-starter-project` repository, as mentioned in Step 5: https://documentation.improbable.io/gdk-for-unity/docs/fps-1-set-up#section-clone-the-fps-starter-project-repository

**Comment by Olaowo** [comment]
> The `spatialos/gdk-for-unity` repository is where the GDK source lives before we publish the individual packages. It does not contain the FPS or Blank projects, which live in different repositories of their own.
> 
> To try the FPS project, you should be cloning the `spatialos/gdk-for-unity-fps-starter-project` repository, as mentioned in Step 5: https://documentation.improbable.io/gdk-for-unity/docs/fps-1-set-up#section-clone-the-fps-starter-project-repository

Got it, saw my mistake thanks
