### ISSUE TITLE
`Kernel 'KMainTopRight' not found UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

### ISSUE THREAD

**Issue by BasWilson** [spatialos/gdk-for-unity-fps-starter-project#5]
We are accepting issues and we want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Describe your issue.
On opening of the unity worker in Unity Editor 2018.2.8f1 there is this error:
`Kernel 'KMainTopRight' not found
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`
## Expected behaviour

I think it should not be there.
## Current behaviour

This error makes it unable to build or do a Local Launch.
## Steps to reproduce

1. Clone this repo.
2. Open the Unity Worker in Unity 2018.2.8f1

## Environment

Trying to do a Local Launch in unity with the GDK

[spatial_20181009T133735.log](https://github.com/spatialos/gdk-for-unity-fps-starter-project/files/2460231/spatial_20181009T133735.log)

Windows 10 Home, Unity 2018.2.8f1

**Comment by jamiebrynes7** [comment]
This error originates from the High Definition Render Pipeline, but only when there are code compilation errors. If you look back in the Console you should see other errors.

Did you clone the `gdk-for-unity` repository side-by-side before opening the project? We will have docs on the setup process soon.

Or I've just merged in some setup scripts that you can run

**Comment by jamiebrynes7** [comment]
Closing this as the docs are **live**!
